export const COMMITS_LOADED = 'COMMITS_LOADED';
export const ALL_CHANGED_FILES_LOADED = 'FILES_LOADED';
export const COMMIT_SELECTED = 'COMMIT_SELECTED';
<<<<<<< HEAD
export const FILE_SELECTED = 'FILE_SELECTED';
=======
export const HISTORY_FILE_SELECTED = 'HISTORY_FILE_SELECTED';
export const CHANGED_FILE_SELECTED = 'CHANGED_FILE_SELECTED';
>>>>>>> Backend
export const CHANGE_REPOSITORY = 'CHANGE_REPOSITORY';
export const CHANGE_BRANCH = 'CHANGE_BRANCH';
export const CHANGE_REPOSITORY_BRANCHES = 'CHANGE_REPOSITORY_BRANCHES';
export const CHANGE_BRANCH_COMMITS = 'CHANGE_BRANCH_COMMITS';
<<<<<<< HEAD
export const SET_ALL_COMMITS = 'SET_ALL_COMMITS'
export const CURRENT_REPO_PATH = 'CURRENT_REPO_PATH'
=======
export const SET_ALL_COMMITS = 'SET_ALL_COMMITS';
export const CURRENT_REPO_PATH = 'CURRENT_REPO_PATH';
>>>>>>> Backend
