export const COMMITS_LOADED = 'COMMITS_LOADED';
export const CHANGE_REPOSITORY = 'CHANGE_REPOSITORY'
export const CHANGE_BRANCH = 'CHANGE_BRANCH'
export const CHANGE_REPOSITORY_BRANCHES = 'CHANGE_REPOSITORY_BRANCHES'
export const CHANGE_BRANCH_COMMITS = 'CHANGE_BRANCH_COMMITS'
